from enum import Enum

class ChordType(Enum):
    MAJOR = 1
    MINOR = 2
    DIMINISHED = 3
    AUGMENTED = 4
    DOMINANT_SEVENTH = 5
    MAJOR_SEVENTH = 6
    MINOR_SEVENTH = 7
    HALF_DIMINISHED_SEVENTH = 8
    DIMINISHED_SEVENTH = 9
    MINOR_MAJOR_SEVENTH = 10
    AUGMENTED_MAJOR_SEVENTH = 11
    AUGMENTED_SEVENTH = 12
    